######################################################################
# Automatically generated by qmake (2.01a) ?? 2? 27 07:00:58 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += QtHello.cpp
