######################################################################
# Automatically generated by qmake (2.01a) ?? 3? 13 14:42:02 2013
######################################################################
QT += network

TEMPLATE = app
TARGET = 
DEPENDPATH += .
DEPENDPATH += ../../Log
INCLUDEPATH += .
INCLUDEPATH += ../../Log

# Input
HEADERS += net.h
SOURCES += net.cpp test.cpp log.cpp
