######################################################################
# Automatically generated by qmake (2.01a) ?? 3? 15 03:05:44 2013
######################################################################
QT += network

TEMPLATE = lib
CONFIG += staticlib
DEPENDPATH += .
DEPENDPATH += ../../Log
DEPENDPATH += ../

INCLUDEPATH += .
INCLUDEPATH += ../../Log
INCLUDEPATH += ../

# Input
HEADERS += net.h log.h prot.h autotype.h String.h
SOURCES += net.cpp log.cpp prot.cpp
